@Library('my-shared-library') _

REPO_URL = 'https://github.com/YOUR_ORG_NAME/YOUR_REPO_NAME.git'
BRANCH = 'main'

def params = [
    REPO_URL: REPO_URL
    BRANCH: BRANCH
]

// Calling Global Variable
runPipeline(params)
